### ISSUE TITLE
AssertionError: inputs must be flattened

### ISSUE THREAD

**Issue by small-zeng** [theNded/torch-ash#22]
Thanks for your work,   What is the problem？

python demo/train_scene_recon.py --path datatset/scene0050_00/samples/ --voxel_size 0.015 --depth_type learned
Loading frame-004640.color.npy: 100%|████████████████████████████| 465/465 [00:08<00:00, 53.80it/s]
Generating rays for image 464: 100%|█████████████████████████████| 465/465 [00:13<00:00, 35.17it/s]
Transforming normals for image 464: 100%|███████████████████████| 465/465 [00:04<00:00, 115.21it/s]
voxel_size=0.015
Fuse frame 0:   0%|                                                        | 0/465 [00:00<?, ?it/s]/opt/anaconda3/envs/sdfstudio/lib/python3.8/site-packages/ash/core.py:145: UserWarning: keys are not int32, conversion might reduce precision.
  warnings.warn("keys are not int32, conversion might reduce precision.")
Fuse frame 464: 100%|████████████████████████████████████████████| 465/465 [00:22<00:00, 20.54it/s]
after pruning: 15052
hash map size after pruning: 15052
  0%|                                                                    | 0/20001 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "demo/train_scene_recon.py", line 302, in <module>
    result = model(rays_o, rays_d, ray_norms, near=0.3, far=5.0, jitter=jitter)
  File "/opt/anaconda3/envs/sdfstudio/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "demo/train_scene_recon.py", line 111, in forward
    weights = nerfacc.render_weight_from_density(
  File "/opt/anaconda3/envs/sdfstudio/lib/python3.8/site-packages/nerfacc/volrend.py", line 358, in render_weight_from_density
    trans, alphas = render_transmittance_from_density(
  File "/opt/anaconda3/envs/sdfstudio/lib/python3.8/site-packages/nerfacc/volrend.py", line 261, in render_transmittance_from_density
    trans = torch.exp(-exclusive_sum(sigmas_dt, packed_info))
  File "/opt/anaconda3/envs/sdfstudio/lib/python3.8/site-packages/nerfacc/scan.py", line 94, in exclusive_sum
    assert inputs.dim() == 1, "inputs must be flattened."
AssertionError: inputs must be flattened.

**Comment by theNded** [comment]
This sounds like a nerfacc version mismatch. Would you please provide your environment setup? Thank you!

**Comment by small-zeng** [comment]
Thank you , I sovle the problem by using nerfacc=0.4.0
